defaults:
  - gp: kermut
  - _self_
  - override hydra/job_logging: disabled  # Prevents creation of .log file from Hydra

DMS_idx: ???
split_method: ???
DMS_data_folder: data/substitutions_singles
DMS_reference_file_path: reference_files/DMS_substitutions.csv
output_scores_folder: model_scores/supervised_substitutions
auxiliary_data_folder: proteingym/baselines/kermut/data


seed: 2024
progress_bar: false
overwrite: false
standardize: true
use_gpu: true

# Disables Hydra logging functionality
hydra:
  output_subdir: null
  job:
    chdir: false
  run:
    dir: .

  